[package]
name = "serde-tests"
version = "0.1.0"
authors = ["Kevin Yeh <kevinyeah@utexas.edu>"]
build = "build.rs"


[dependencies]
serde = "0.9"
bson = { path = "..", features = ["serde"] }

[build-dependencies]
syntex = "0.46"
serde_codegen = "0.9"

[lib]
name = "serde_tests"
path = "lib.rs"

[[test]]
name = "serde"
path = "test.rs"
